# Backend configuration for Application Load Balancer
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: notes-app-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 8000
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 3600
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
  logging:
    enable: true
    sampleRate: 1.0
  iap:
    enabled: false
  cdn:
    enabled: false
  securityPolicy:
    name: "notes-app-security-policy"